# Makefile for the Linux video drivers.
# 8 Mars 2021, Patrick H. E. Foubet, <mailto:pfoubet@seriane.org>

# Each configuration option enables a list of files.

obj-y                             += mod5a.o
